// <auto-generated />
using System;
using Mes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MesDbContext))]
    partial class MesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mes.Domain.Auditing.BusinessAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ActorRolesSnapshot")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("AuthorizedRole")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("BusinessObjectId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("BusinessObjectType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Capability")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("BusinessObjectType", "BusinessObjectId", "OccurredAtUtc");

                    b.ToTable("BusinessAuditRecords", "audit", t =>
                        {
                            t.HasTrigger("TR_BusinessAuditRecords_AppendOnly");

                            t.HasCheckConstraint("CK_BusinessAuditRecords_AuthorizedRole", "[AuthorizedRole] IS NULL OR [AuthorizedRole] IN ('Planner', 'ProcessEngineer', 'Operator', 'LineSupervisor', 'QualityEngineer', 'MaterialHandler', 'SystemAdministrator', 'OperationsManager')");

                            t.HasCheckConstraint("CK_BusinessAuditRecords_Result", "[Result] IN ('Succeeded', 'Denied')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Mes.Domain.Execution.ManufacturingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("CorrectsEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorrectsEventId");

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAtUtc");

                    b.ToTable("ManufacturingEvents", "mes", t =>
                        {
                            t.HasTrigger("TR_ManufacturingEvents_AppendOnly");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Mes.Domain.Execution.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("ProductionOrders", "mes", t =>
                        {
                            t.HasCheckConstraint("CK_ProductionOrders_PlannedQuantity", "[PlannedQuantity] > 0");

                            t.HasCheckConstraint("CK_ProductionOrders_Status", "[Status] IN ('Created', 'Released', 'Closed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Mes.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PrimaryRole")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts", "security", t =>
                        {
                            t.HasCheckConstraint("CK_UserAccounts_PasswordHash", "[PasswordHash] IS NULL OR LEN([PasswordHash]) > 0");

                            t.HasCheckConstraint("CK_UserAccounts_PrimaryRole", "[PrimaryRole] IS NULL OR [PrimaryRole] IN ('Planner', 'ProcessEngineer', 'Operator', 'LineSupervisor', 'QualityEngineer', 'MaterialHandler', 'SystemAdministrator', 'OperationsManager')");
                        });
                });

            modelBuilder.Entity("Mes.Domain.Identity.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("UserAccountId", "Role");

                    b.ToTable("UserAccountRoles", "security", t =>
                        {
                            t.HasCheckConstraint("CK_UserAccountRoles_Role", "[Role] IN ('Planner', 'ProcessEngineer', 'Operator', 'LineSupervisor', 'QualityEngineer', 'MaterialHandler', 'SystemAdministrator', 'OperationsManager')");
                        });
                });

            modelBuilder.Entity("Mes.Domain.MasterData.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TraceabilityMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Materials", "mes", t =>
                        {
                            t.HasCheckConstraint("CK_Materials_TraceabilityMode", "[TraceabilityMode] IN ('None', 'Lot', 'Serial')");
                        });
                });

            modelBuilder.Entity("Mes.Domain.Auditing.BusinessAuditRecord", b =>
                {
                    b.HasOne("Mes.Domain.Identity.UserAccount", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Mes.Domain.Execution.ManufacturingEvent", b =>
                {
                    b.HasOne("Mes.Domain.Execution.ManufacturingEvent", "CorrectsEvent")
                        .WithMany()
                        .HasForeignKey("CorrectsEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CorrectsEvent");
                });

            modelBuilder.Entity("Mes.Domain.Execution.ProductionOrder", b =>
                {
                    b.HasOne("Mes.Domain.MasterData.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Mes.Domain.Identity.UserRoleAssignment", b =>
                {
                    b.HasOne("Mes.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Mes.Domain.Identity.UserAccount", b =>
                {
                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
