// <auto-generated />
using System;
using Mes.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mes.Api.Data.Migrations
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20260729090516_InitialLegacyBaseline")]
    partial class InitialLegacyBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mes.Api.Execution.ComponentBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ComponentMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentSerialNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OperatorUserName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSerialId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComponentMaterialId");

                    b.HasIndex("ComponentSerialNo")
                        .IsUnique();

                    b.HasIndex("ProductSerialId");

                    b.ToTable("ComponentBindings");
                });

            modelBuilder.Entity("Mes.Api.Execution.FinishedGoodsInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId")
                        .IsUnique();

                    b.ToTable("FinishedGoodsInventories");
                });

            modelBuilder.Entity("Mes.Api.Execution.LineSideInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId")
                        .IsUnique();

                    b.ToTable("LineSideInventories");
                });

            modelBuilder.Entity("Mes.Api.Execution.ProductSerial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CurrentProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SerialNo")
                        .IsUnique();

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ProductSerials");
                });

            modelBuilder.Entity("Mes.Api.Execution.SerialPassRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperatorUserName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSerialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("WorkStationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProcessStepId");

                    b.HasIndex("ProductSerialId");

                    b.HasIndex("WorkStationId");

                    b.ToTable("SerialPassRecords");
                });

            modelBuilder.Entity("Mes.Api.Execution.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompletedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FinishedMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FrozenBomVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("FrozenRouteVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("InProcessSerialCount")
                        .HasColumnType("int");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("PlannedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("ProcessRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ScrappedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("FinishedMaterialId");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("ProcessRouteId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("Mes.Api.Execution.WorkOrderIssueLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConsumedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("IssuedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PendingQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("WorkOrderId", "MaterialId")
                        .IsUnique();

                    b.ToTable("WorkOrderIssueLines");
                });

            modelBuilder.Entity("Mes.Api.Identity.BusinessAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActorUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Mes.Api.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanViewOpsOverview")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mes.Api.Integration.ErpOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("ErpOutboxMessages");
                });

            modelBuilder.Entity("Mes.Api.MasterData.Bom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FinishedMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("FinishedMaterialId");

                    b.ToTable("Boms");
                });

            modelBuilder.Entity("Mes.Api.MasterData.BomLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComponentMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityPer")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("ComponentMaterialId");

                    b.ToTable("BomLines");
                });

            modelBuilder.Entity("Mes.Api.MasterData.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinishedGood")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKeyComponent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("RequiresSerialNumber")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Mes.Api.MasterData.ProcessRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("FinishedMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FinishedMaterialId");

                    b.ToTable("ProcessRoutes");
                });

            modelBuilder.Entity("Mes.Api.MasterData.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsQualityStep")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ProcessRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ReworkToSequence")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessRouteId", "Sequence")
                        .IsUnique();

                    b.ToTable("ProcessSteps");
                });

            modelBuilder.Entity("Mes.Api.MasterData.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("Mes.Api.MasterData.WorkStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoundProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BoundProcessStepId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductionLineId");

                    b.ToTable("WorkStations");
                });

            modelBuilder.Entity("Mes.Api.Execution.ComponentBinding", b =>
                {
                    b.HasOne("Mes.Api.MasterData.Material", "ComponentMaterial")
                        .WithMany()
                        .HasForeignKey("ComponentMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mes.Api.Execution.ProductSerial", "ProductSerial")
                        .WithMany("ComponentBindings")
                        .HasForeignKey("ProductSerialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentMaterial");

                    b.Navigation("ProductSerial");
                });

            modelBuilder.Entity("Mes.Api.Execution.FinishedGoodsInventory", b =>
                {
                    b.HasOne("Mes.Api.MasterData.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Mes.Api.Execution.LineSideInventory", b =>
                {
                    b.HasOne("Mes.Api.MasterData.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Mes.Api.Execution.ProductSerial", b =>
                {
                    b.HasOne("Mes.Api.Execution.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Mes.Api.Execution.SerialPassRecord", b =>
                {
                    b.HasOne("Mes.Api.MasterData.ProcessStep", "ProcessStep")
                        .WithMany()
                        .HasForeignKey("ProcessStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mes.Api.Execution.ProductSerial", "ProductSerial")
                        .WithMany("PassRecords")
                        .HasForeignKey("ProductSerialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Api.MasterData.WorkStation", "WorkStation")
                        .WithMany()
                        .HasForeignKey("WorkStationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProcessStep");

                    b.Navigation("ProductSerial");

                    b.Navigation("WorkStation");
                });

            modelBuilder.Entity("Mes.Api.Execution.WorkOrder", b =>
                {
                    b.HasOne("Mes.Api.MasterData.Bom", "Bom")
                        .WithMany()
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mes.Api.MasterData.Material", "FinishedMaterial")
                        .WithMany()
                        .HasForeignKey("FinishedMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mes.Api.MasterData.ProcessRoute", "ProcessRoute")
                        .WithMany()
                        .HasForeignKey("ProcessRouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bom");

                    b.Navigation("FinishedMaterial");

                    b.Navigation("ProcessRoute");
                });

            modelBuilder.Entity("Mes.Api.Execution.WorkOrderIssueLine", b =>
                {
                    b.HasOne("Mes.Api.MasterData.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mes.Api.Execution.WorkOrder", "WorkOrder")
                        .WithMany("IssueLines")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Mes.Api.MasterData.Bom", b =>
                {
                    b.HasOne("Mes.Api.MasterData.Material", "FinishedMaterial")
                        .WithMany()
                        .HasForeignKey("FinishedMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinishedMaterial");
                });

            modelBuilder.Entity("Mes.Api.MasterData.BomLine", b =>
                {
                    b.HasOne("Mes.Api.MasterData.Bom", "Bom")
                        .WithMany("Lines")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Api.MasterData.Material", "ComponentMaterial")
                        .WithMany()
                        .HasForeignKey("ComponentMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bom");

                    b.Navigation("ComponentMaterial");
                });

            modelBuilder.Entity("Mes.Api.MasterData.ProcessRoute", b =>
                {
                    b.HasOne("Mes.Api.MasterData.Material", "FinishedMaterial")
                        .WithMany()
                        .HasForeignKey("FinishedMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinishedMaterial");
                });

            modelBuilder.Entity("Mes.Api.MasterData.ProcessStep", b =>
                {
                    b.HasOne("Mes.Api.MasterData.ProcessRoute", "ProcessRoute")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessRoute");
                });

            modelBuilder.Entity("Mes.Api.MasterData.WorkStation", b =>
                {
                    b.HasOne("Mes.Api.MasterData.ProcessStep", "BoundProcessStep")
                        .WithMany()
                        .HasForeignKey("BoundProcessStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mes.Api.MasterData.ProductionLine", "ProductionLine")
                        .WithMany("Stations")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoundProcessStep");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("Mes.Api.Execution.ProductSerial", b =>
                {
                    b.Navigation("ComponentBindings");

                    b.Navigation("PassRecords");
                });

            modelBuilder.Entity("Mes.Api.Execution.WorkOrder", b =>
                {
                    b.Navigation("IssueLines");
                });

            modelBuilder.Entity("Mes.Api.MasterData.Bom", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Mes.Api.MasterData.ProcessRoute", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Mes.Api.MasterData.ProductionLine", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
